apiVersion: v1
kind: Service
metadata: 
  name: blue-green
  labels: 
    name: blue-green
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: 
    name: blue-green
    version: "0.0.2"
  type: LoadBalancer